# Generated by Django 3.2.4 on 2021-07-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20210706_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Forms',
        ),
    ]
