# Generated by Django 3.2.4 on 2021-07-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_rename_form_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='payment_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
