# Generated by Django 3.2.4 on 2021-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_forms_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='payment_id',
            new_name='order_id',
        ),
    ]
