# Generated by Django 3.2.4 on 2021-07-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_auto_20210706_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
