# Generated by Django 3.2.4 on 2021-07-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_alter_forms_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='made_by',
        ),
    ]
