# Generated by Django 3.2.4 on 2021-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0013_auto_20210709_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forms',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
