# Generated by Django 3.2.4 on 2021-07-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0017_auto_20210709_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='amount',
            field=models.FloatField(),
        ),
    ]
